pkg/landscaper/component.go, pkg/landscaper/component_provider.go, pkg/landscaper/executor.go, pkg/landscaper/executor_test.go
an attempt to solve https://github.com/Eneco/landscaper/issues/15
changes:
* change `[]*Component`to `map[string]*Component`
* alias `Components` to `map[string]*Component`
* initialize `Components` via `Components{}` instead of `make(Components)` (why expose that `Components` is actually a map 😄 )
* remove now obsolete on-the-fly slice-to-map conversions
=> Convert component slices to maps

docker/Dockerfile
This updates the Helm client to the latest 2.2.x version.
It also updates the Kubernetes env var to the latest 1.5 release
=> Update Helm client

cmd/apply.go, pkg/landscaper/environment.go
This allows running `landscaper` as a controller in the cluster that can constantly watch a source of landscaped files and apply them to the cluster.
It provides a boolean `--loop` flag to the `apply` command which will run the usual apply code in a loop. Delay between the iterations can be controlled with `--loop-interval`, see below for an example. The default for `--loop` is false so there's no change to the current behaviour without that flag.
An example manifest file how this can be setup with a Git repository syncer as a sidecar on a private repository is shown below. It works as expected but there's one gotcha: the very first landscaper run after pod creation will remove everything as the Git repo hasn't been synced yet. But that can be fixed in another PR.
```yaml
apiVersion: …
```
=> Provide a way to run landscaper as a controller

pkg/landscaper/environment.go
Helm uses the HELM_HOST environment variable for the tiller address if it exists instead of looking for a pod in Kubernetes (it can also be specified with --host)
This makes landscaper look for the HELM_HOST environment variable and use it directly if it's set instead of creating the tunnel.
=> feat: use HELM_HOST if defined

pkg/landscaper/executor.go
I noticed while testing out this tool that it was reporting that my namespace had changed during updates... even though that wasn't true.
=> Move namespace difference log into conditional

pkg/landscaper/release.go, pkg/landscaper/state_provider_test.go, test/landscapes/no-version/hello-world.yaml
This allows the Release.Version to be unset.
Addresses https://github.com/Eneco/landscaper/issues/73
LMK if there are any changes you'd like or any ways I can clean up the tests.
(FYI: I'm new to go)
=> Allow landscape version to be optional

cmd/apply.go, pkg/landscaper/environment.go
Hi,
this small PR adds support for using Tiller in an specific namespace. If you don't set any namespace landscaper will use kube-system one as before.
=> landscaper support for namespaced Tiller

README.md, cmd/apply.go, pkg/landscaper/environment.go, pkg/landscaper/executor.go, pkg/landscaper/executor_test.go
* Uses helm's option to wait until created resources are ready which in turn
makes landscaper only exit when all components are ready.
* Adds 2 parameters:
--wait instructs helm client to wait for resource to become ready (helm
equivalent --wait, defaults to false)
--wait-timeout time to wait for individual kubernetes operation (helm
equivalent --timeout, defaults to 5min)
=> feat: wait for components to be ready

pkg/landscaper/state_provider.go
I have a chart that uses dependency aliases (https://docs.helm.sh/developing_charts/#alias-field-in-requirements-yaml).
Landscaper was able to deploy it correctly but it would always try to update it, even when there was no changes at all. I investigated a little and found out that landscaper doesn't load the chart values correctly when using aliases. This breaks the diff between helm state and file state and makes Landscaper attempt an update.
By looking at Helm code I found out that the chart dependencies are actually updated in the "chartutil.ProcessRequirementsEnabled" method. This will add dependencies for aliases but also remove disable charts. I only tested this for dependencies aliases but I think that removing disabled charts is also something we want to do.
I have not added …
=> feat: Process requirements to support dependency aliases

pkg/landscaper/state_provider.go
During `Components` load skipping what is not part of target namespace, during run.
=> fix(issue93): Skipping non-target namespace.

README.md, cmd/apply.go, glide.lock, glide.yaml, pkg/landscaper/environment.go, pkg/landscaper/secrets.go, pkg/landscaper/secrets_azure.go
I have added a simple command line flag to specify (and implicitly enable) the azure key vault. I don't think this approach will scale as more external service integrations are added (hashicorp vault etc).
=> feat: add azure keyvault support

README.md, cmd/apply.go, pkg/landscaper/component.go, pkg/landscaper/component_test.go, pkg/landscaper/configuration.go, pkg/landscaper/environment.go, pkg/landscaper/executor_test.go, pkg/landscaper/state_provider.go, pkg/landscaper/state_provider_test.go, test/landscapes/environments/hello-world.yaml
This is a proposal for managing differences between environments when using the landscaper. It adds another section `environments` to the desired state file with optional overrides for values in the `configuration` section. The environments are named, and can be selected with the `--env` flag at deployment time. 
See the updates the the README for an example.
=> Environment overrides

cmd/apply.go, cmd/landscaper.go, glide.lock, glide.yaml, pkg/landscaper/chart.go, pkg/landscaper/environment.go, pkg/landscaper/executor.go, pkg/landscaper/secrets.go, pkg/landscaper/secrets_azure.go, pkg/landscaper/state_provider.go
landscaper currently fails building because the logrus import changed.
This is a bit hacky as I modify `glide.lock` directly which breaks the hashing. Though, it was broken before, so...
How:
* update logrus to 1.0 and rename imports to lowercase
* pin `github.com/x-cray/logrus-prefixed-formatter` to the newest version which references it by lowercase too
/cc @otaviof
=> Update logrus and pin one dependency

.travis.yml, README.md, glide.lock, glide.yaml, pkg/landscaper/environment.go
Updated helm to 2.7.2 and Kubernetes to 1.8
Quite a lot of updates in the .lock file as it seems that the latest Helm update didn't actually update the glide.lock file.
https://github.com/Eneco/landscaper/commit/c7ca2e5399a271d983fe1f0659ce06610b64f4da
=> chore: move to helm 2.7.2

README.md, cmd/apply.go, pkg/landscaper/environment.go, pkg/landscaper/state_provider.go, pkg/landscaper/state_provider_test.go, test/landscapes/environments/global-override.yaml
This allows specifying a configuration override file that will override chart and component defaults, but not environment overrides in the component.
My use case is I want to apply a global configuration to all components deployed to a particular environment, eg.:
ingressSuffix: 'staging.example.com'
environment:   'staging'
=> feat: add global configuration override file support

example/README.md, pkg/landscaper/executor.go
This PR tries to provide a workaround for the issue: #101 
Before:
```
Landscaper would first delete the secrets of a component in the update, regardless if new secrets are provided or not
```
Now:
```
Landscaper would first delete the secrets of a component in the update, regardless if new secrets are provided or not.
Unless the flag "--disable deleteSecrets" is provided during the apply. But in the case, new secrets are provided it will delete the old secrets regardless of the flag.
```
=> Provide a way to avoid deleting the secrets during the update

README.md, pkg/landscaper/component.go, pkg/landscaper/component_test.go, pkg/landscaper/configuration.go, pkg/landscaper/executor.go, pkg/landscaper/executor_test.go, pkg/landscaper/mocks_test.go, pkg/landscaper/secrets.go, pkg/landscaper/secrets_azure.go, pkg/landscaper/state_provider.go, pkg/landscaper/state_provider_test.go, test/landscapes/secrets/secret-list.yaml, test/landscapes/secrets/secret-map.yaml, test/landscapes/secrets/secret-none.yaml
This feature makes it easier to deal with charts or containers that expect specific keys in secret objects. For example an nginx ingress controller expects basic auth credentials to be `auth: <list of htpasswds>`.
The unmarshalling of the secret list/map is done manually, and the `Secret` and `SecretsRaw` fields are cleaned after the `SecretValues` are fetched so that they are ignored by the compare.
=> feat: support secrets as a map with alternate keys

Gopkg.lock, Gopkg.toml, README.md, pkg/landscaper/environment.go, pkg/landscaper/executor.go, pkg/landscaper/mocks_test.go, pkg/landscaper/secrets.go
Fixes #121 
I think I need a hand here.
This is the first time I do GoLang, I sort out all the dependencies and tests are passing but Landscaper can't retrieve Tiller version for some reason I don't understand
I'll appreciate some guidance here if you have some time
Thanks!
=> Add Kubernetes 1.9 and Helm 2.8.2 support

pkg/landscaper/executor.go, pkg/landscaper/executor_test.go
When only secrets have changed Landscaper performs a "forced update" which deletes and creates the release.
This operation fails when "create" and/or "delete" stages are disabled. This PR allows to delete and create the component which has been forced to be updated
=> Fix forced updates when "disable" and/or "create" stages are disbled

README.md, pkg/landscaper/state_provider.go
Currently, Landscaper fails to list Helm releases throwing the following error
```
time="2018-09-26T15:00:38Z" level=debug msg=listHelmReleases
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x11f5d4e]
goroutine 1 [running]:
github.com/eneco/landscaper/pkg/landscaper.(*helmStateProvider).listHelmReleases(0xc420b2b530, 0x1, 0x1, 0x0, 0x0, 0x0)
/root/go/src/github.com/eneco/landscaper/pkg/landscaper/state_provider.go:324 +0x18e
github.com/eneco/landscaper/pkg/landscaper.(*helmStateProvider).Components(0xc420b2b530, 0xc420b2b560, 0x0, 0x0)
...
```
A colleague found [this issue](https://github.com/helm/helm/issues/3625) on Helm repo and the related [merged PR](https://github.com/helm/helm/pull/4325)
I …
=> "Cherry pick" Helm fix for go panic Helm lists releases

.travis.yml
[landscaper brew formula ](https://github.com/Homebrew/homebrew-core/pull/47631)is using go 1.13 for building the artifact (which works well), so bump the golang version for Travis.
=> Bump golang to v1.13 for Travis
